import Remember from "../images/remember.svg"
import Mark_johnson from "../images/mark-johnson.png"
import Rate_img from "../images/rate-img.png"
import Traking_img from "../images/traking.png"
import Sales_img from "../images/sales.png"
import Active_img from "../images/activ-users.png"
import Project_img from "../images/project.png"
import Orders_img from "../images/orders.png"
import Avvt from "../images/avvt.png"
import HtmlIcon from "../images/html.svg"
import Esthera from "../images/Esthera.svg"
import Freduardo from "../images/Freduardo.svg"
import Daniel from "../images/Daniel.svg"
import Alex from "../images/Alexa.svg"
import Laurent from "../images/Laurent.svg"
import Mark from "../images/Mark.svg"

export { Esthera , Freduardo, Daniel,Alex, Laurent, Mark,HtmlIcon, Avvt,Remember, Mark_johnson, Rate_img, Traking_img, Sales_img, Active_img, Project_img, Orders_img}